#!/usr/bin/env python3
"""
judgmentops.py — Minimal local demonstration CLI for JudgmentOps.

This is a thin artifact to show how the judgment protocol can be turned into
actionable commands. It uses simple heuristics only. No network calls.

Commands:
  create-intent-contract --input FILE --output FILE
  create-quality-gate    --input FILE --output FILE
  create-failure-memory  --input FILE --output FILE
  redact                 --input FILE --output FILE --report FILE

All processing is local. Output is deterministic given the same input.
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List


def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _write_json(path: Path, data: Dict[str, Any]) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def _write_text(path: Path, text: str) -> None:
    path.write_text(text, encoding="utf-8")


def cmd_create_intent_contract(args: argparse.Namespace) -> int:
    src = Path(args.input)
    if not src.exists():
        print(f"ERROR: input not found: {src}", file=sys.stderr)
        return 1

    text = _read_text(src).lower()

    # Very simple heuristics for the demo
    scope = "Main dashboard view for authenticated users on mobile. Focus on load performance and error rate."
    if "login" in text:
        scope = "Login flow (credential and OAuth) on mobile viewports. Includes network, rendering, and client validation."
    if "export" in text or "csv" in text:
        scope = "Transactions table export functionality (CSV) with date range and related entities option."

    success = [
        "p95 time-to-interactive on 4G mobile for the primary flow under target load is within stated bounds.",
        "Error rate on the primary user action remains below the threshold defined in the contract."
    ]
    non_goals = [
        "Visual or design system changes.",
        "Modifications to backend data models beyond what is required for the stated scope.",
        "New third-party dependencies or scripts on the critical path."
    ]
    constraints = [
        "Bundle size increase must stay under the declared limit.",
        "Existing CSP, rate limiting, and data classification rules must continue to be satisfied."
    ]

    contract = {
        "id": f"ic-demo-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M')}",
        "title": "Demo intent contract generated from input",
        "source": str(src),
        "scope": scope,
        "success_criteria": success,
        "non_goals": non_goals,
        "constraints": constraints,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "author": "judgmentops-demo-cli",
        "notes": "Generated by simple heuristic parser for demonstration purposes only. Review and edit before real use."
    }

    _write_json(Path(args.output), contract)
    print(f"Wrote intent contract to {args.output}")
    return 0


def cmd_create_quality_gate(args: argparse.Namespace) -> int:
    src = Path(args.input)
    if not src.exists():
        print(f"ERROR: input not found: {src}", file=sys.stderr)
        return 1

    text = _read_text(src).lower()
    contract_id = "ic-demo-unknown"
    if "ic-" in text:
        m = re.search(r"ic-[a-z0-9-]+", text)
        if m:
            contract_id = m.group(0)

    criteria: List[Dict[str, str]] = [
        {
            "description": "Primary performance or correctness target for the declared scope",
            "evidence_type": "synthetic_monitoring",
            "pass_condition": "Measured value meets or exceeds the threshold in the intent contract"
        },
        {
            "description": "No regression on existing automated tests covering the changed surface",
            "evidence_type": "test",
            "pass_condition": "All relevant tests in CI are green"
        },
        {
            "description": "Human review of the observable user path under the new behavior",
            "evidence_type": "manual_review",
            "pass_condition": "Designated reviewer signs off with evidence attached"
        }
    ]

    gate = {
        "id": f"qg-demo-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M')}",
        "intent_contract_id": contract_id,
        "criteria": criteria,
        "blocking": True,
        "notes": "Generated by simple heuristic parser. Tailor criteria to the actual intent contract before use."
    }

    _write_json(Path(args.output), gate)
    print(f"Wrote quality gate to {args.output}")
    return 0


def cmd_create_failure_memory(args: argparse.Namespace) -> int:
    src = Path(args.input)
    if not src.exists():
        print(f"ERROR: input not found: {src}", file=sys.stderr)
        return 1

    text = _read_text(src)

    summary = "Agent change produced locally correct behavior that violated broader system or product invariants."
    if "stale" in text.lower() or "cache" in text.lower():
        summary = "Caching change caused stale data for users because invalidation was incomplete across update surfaces."
    if "export" in text.lower():
        summary = "Export feature change expanded data surface without updating consent, classification, or audit requirements."

    entry = {
        "id": f"fm-demo-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M')}",
        "date": datetime.now(timezone.utc).date().isoformat(),
        "summary": summary,
        "agent_behavior": "Implemented the narrow request using only the code and tests visible in the provided context.",
        "surface_symptom": "Downstream users, support, or metrics revealed the gap after merge.",
        "root_judgment_failure": "Missing or incomplete intent contract, quality gate, or failure memory consultation for cross-surface or product-level invariants.",
        "preventive_rule": "Before implementing any change that can affect user-visible state, data classification, or cross-module invariants, the agent must be given (and must consult) an explicit intent contract plus relevant prior failure memory. Quality gates must include product-level success criteria, not only unit test passage.",
        "related_cases": ["JC-003", "JC-013", "JC-014", "JC-015"],
        "severity": "medium",
        "tags": ["demo", "heuristic"]
    }

    _write_json(Path(args.output), entry)
    print(f"Wrote failure memory entry to {args.output}")
    return 0


REDACTION_PATTERNS = [
    (re.compile(r"(?i)/(?:Users|home)/[^ \n\"']+"), "[REDACTED_PRIVATE_LOCATION]"),
    (re.compile(r"(?i)[A-Z]:\\[^ \n\"']+"), "[REDACTED_PRIVATE_LOCATION]"),
    (re.compile(r"(?i)acme-internal|acme-corp-internal|secret-project-xyz|internal-codename-x"), "[REDACTED]"),
    (re.compile(r"(?i)FAKE_TOKEN_DO_NOT_USE_[a-z0-9]{8,}|test_[a-z0-9]{16,}"), "[REDACTED_TOKEN]"),
    (re.compile(r"(?i)incident\s+INC-[0-9]+|ticket\s+[A-Z]+-[0-9]+"), "[REDACTED_INTERNAL_TICKET]"),
    (re.compile(r"(?i)billing-orchestrator-v2.*\.example"), "[REDACTED_INTERNAL_HOST]"),
]


def cmd_redact(args: argparse.Namespace) -> int:
    src = Path(args.input)
    if not src.exists():
        print(f"ERROR: input not found: {src}", file=sys.stderr)
        return 1

    text = _read_text(src)
    report: Dict[str, Any] = {
        "id": f"rr-demo-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M')}",
        "input_source": str(src),
        "matches": [],
        "human_review_required": True,
        "notes": "Best-effort redaction using simple patterns. Always perform human review before publishing any output."
    }

    redacted = text
    for pattern, replacement in REDACTION_PATTERNS:
        for m in pattern.finditer(text):
            match_info = {
                "pattern": pattern.pattern,
                "matched_length": len(m.group(0)),
                "replacement": replacement,
                "start": m.start(),
            }
            report["matches"].append(match_info)
        redacted = pattern.sub(replacement, redacted)

    _write_text(Path(args.output), redacted)
    _write_json(Path(args.report), report)

    print(f"Wrote redacted output to {args.output}")
    print(f"Wrote redaction report to {args.report}")
    if report["matches"]:
        print(f"  {len(report['matches'])} potential internal / secret matches were replaced.")
    else:
        print("  No known internal/secret patterns detected by the demo redactor.")
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="judgmentops",
        description="JudgmentOps minimal local CLI (demo). No network. Heuristic only.",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    # create-intent-contract
    p = subparsers.add_parser(
        "create-intent-contract",
        help="Generate a demo intent contract from a text description (e.g. issue).",
    )
    p.add_argument("--input", required=True, help="Path to input text/markdown file")
    p.add_argument("--output", required=True, help="Path to write intent_contract.json")
    p.set_defaults(func=cmd_create_intent_contract)

    # create-quality-gate
    p = subparsers.add_parser(
        "create-quality-gate",
        help="Generate a demo quality gate (heuristic).",
    )
    p.add_argument("--input", required=True, help="Path to input (intent contract or task text)")
    p.add_argument("--output", required=True, help="Path to write quality_gate.json")
    p.set_defaults(func=cmd_create_quality_gate)

    # create-failure-memory
    p = subparsers.add_parser(
        "create-failure-memory",
        help="Generate a demo failure memory entry from a failure description.",
    )
    p.add_argument("--input", required=True, help="Path to input text describing the failure")
    p.add_argument("--output", required=True, help="Path to write failure_memory.json")
    p.set_defaults(func=cmd_create_failure_memory)

    # redact
    p = subparsers.add_parser(
        "redact",
        help="Apply best-effort redaction to a file and produce a report.",
    )
    p.add_argument("--input", required=True, help="Path to candidate external text/prompt")
    p.add_argument("--output", required=True, help="Path to write redacted version")
    p.add_argument("--report", required=True, help="Path to write redaction_report.json")
    p.set_defaults(func=cmd_redact)

    return parser


def main(argv: List[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
